AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members
  CodeDeployRole:
    Type: String
    Description: IAM role to allow AWS CodeDeploy to manage deployment of AWS Lambda functions
  Stage:
    Type: String
    Description: The name for a project pipeline stage, such as Staging or Prod, for which resources are provisioned and deployed.
    Default: ''
  Application:
    Type: String
    Default: ''

Globals:
  Function:
    AutoPublishAlias: live
    DeploymentPreference:
      Enabled: true
      Type: Canary10Percent5Minutes
      Role: !Ref CodeDeployRole

Resources:
  LingueeProxyController:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Application}-${ProjectId}-LingueeProxyController-${Stage}'
      Handler: index.handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          ENV: !Sub '${Stage}'
      Role:
        Fn::GetAtt:
        - LambdaInvocationRole
        - Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /translation/{src}/{dst}/{query}
            Method: get
      Timeout: 3
      CodeUri: ./lts
  FindDbTranslation:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub '${Application}-${ProjectId}-FindDbTranslation-${Stage}'
      Handler: index.handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          ENV: !Sub '${Stage}'
      CodeUri: ./findDbTranslation
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::416497755919:role/LPS-GetTranslationInDb'
      Tags:
        Project: LPS
  CoordinateTranslationRetrieval:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: !Sub '${Application}-${ProjectId}-CoordinateTranslationRetrieval-${Stage}'
      Description: ''
      Handler: index.handler
      Environment:
        Variables:
          NODE_ENV: !Sub '${Stage}'
      Role:
        Fn::GetAtt:
        - LambdaInvocationRole
        - Arn
      Runtime: nodejs12.x
      CodeUri: ./coordinateTranslationRetrieval
      Timeout: 3
  LambdaInvocationRole:
    Description: Invoke Lambdas
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${Application}-${ProjectId}-LambdaInvocationRole-${Stage}'
      AssumeRolePolicyDocument:
        Statement:
          - 
            Effect: 'Allow'
            Principal: 
              Service: 
                - 'lambda.amazonaws.com'
            Action: 
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/lts -'
      PermissionsBoundary: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/CodeStar_${ProjectId}_PermissionsBoundary'
  LingueeLayer:
    Type: AWS::Serverless::LayerVersion 
    Properties:
      LayerName: LingueeLayer
      ContentUri: 's3://zunge-layers/linguee-layer-custom.zip'
      CompatibleRuntimes:
          - nodejs12.x
      LicenseInfo: 'Available under the MIT-0 license.'
      RetentionPolicy: Retain
  ExpressLayer:
    Type: AWS::Serverless::LayerVersion 
    Properties:
      LayerName: common-dependencies
      Description: Common dependencies
      ContentUri: layers/common/
      CompatibleRuntimes:
        - nodejs12.x
      LicenseInfo: 'Available under the MIT-0 license.'
      RetentionPolicy: Retain



